"""Route constants for the NettFront procurement workflow."""

from __future__ import annotations

NETTFRONT_PROCUREMENT_ROUTE = "/apps/nettfront-beszerzes"
NETTFRONT_PROCUREMENT_PROCESS_ROUTE = f"{NETTFRONT_PROCUREMENT_ROUTE}/process"
NETTFRONT_PROCUREMENT_DOWNLOAD_PREFIX = f"{NETTFRONT_PROCUREMENT_ROUTE}/download"
NETTFRONT_PROCUREMENT_LAUNCH_PREFIX = f"{NETTFRONT_PROCUREMENT_ROUTE}/launch"
NETTFRONT_PROCUREMENT_STOP_PREFIX = f"{NETTFRONT_PROCUREMENT_ROUTE}/stop"
NETTFRONT_PROCUREMENT_PARTS_PREFIX = f"{NETTFRONT_PROCUREMENT_ROUTE}/alkatreszlista"
