from __future__ import annotations

NETTFRONT_ORDER_ROUTE = "/apps/nettfront-rendeles"
NETTFRONT_ORDER_PROCESS_ROUTE = f"{NETTFRONT_ORDER_ROUTE}/process"
NETTFRONT_ORDER_APPROVE_PREFIX = f"{NETTFRONT_ORDER_ROUTE}/approve"
NETTFRONT_ORDER_DOWNLOAD_PREFIX = f"{NETTFRONT_ORDER_ROUTE}/download"
NETTFRONT_ORDER_LAUNCH_PREFIX = f"{NETTFRONT_ORDER_ROUTE}/launch"
NETTFRONT_ORDER_STOP_PREFIX = f"{NETTFRONT_ORDER_ROUTE}/stop"
