"""Routes for the NettFront invoice receiving module."""

from __future__ import annotations


NETTFRONT_INVOICE_ROUTE = "/apps/nettfront-szamla"
NETTFRONT_INVOICE_IMPORT_ROUTE = f"{NETTFRONT_INVOICE_ROUTE}/import"
NETTFRONT_INVOICE_OPEN_ROUTE = f"{NETTFRONT_INVOICE_ROUTE}/open"
NETTFRONT_INVOICE_VIEW_PREFIX = f"{NETTFRONT_INVOICE_ROUTE}/invoice"
NETTFRONT_INVOICE_READ_PREFIX = f"{NETTFRONT_INVOICE_ROUTE}/read"
NETTFRONT_INVOICE_CAMERA_PREFIX = f"{NETTFRONT_INVOICE_ROUTE}/camera"
NETTFRONT_INVOICE_CLOSE_PREFIX = f"{NETTFRONT_INVOICE_ROUTE}/close"
NETTFRONT_INVOICE_XML_PREFIX = f"{NETTFRONT_INVOICE_ROUTE}/batch-xml"
NETTFRONT_INVOICE_SCAN_PREFIX = f"{NETTFRONT_INVOICE_ROUTE}/scan"

NETTFRONT_INVOICE_CHECK_ROUTE = "/apps/nettfront-szamla-ellenorzes"

NETTFRONT_INVOICE_ADMIN_ROUTE = "/apps/admin-nettfront-szamla"
NETTFRONT_INVOICE_ADMIN_EXPORT_PREFIX = f"{NETTFRONT_INVOICE_ADMIN_ROUTE}/export"
NETTFRONT_INVOICE_ADMIN_REOPEN_PREFIX = f"{NETTFRONT_INVOICE_ADMIN_ROUTE}/reopen"
