"""Public API for the manufacturing papers workflow."""

from __future__ import annotations

MANUFACTURING_ACCESS_USER_IDS = frozenset({"manufacturer"})

from .common import (
    available_production_entries,
    available_production_numbers,
    complete_issued_row_edit,
    latest_production_number,
    load_partial_quantity_state,
    load_production_bundle,
    load_selection_state,
    production_folder,
    save_partial_quantity_state,
    save_selection_state,
    save_pantolo_missing_description,
    sync_pantolo_missing_state,
)
from .config import configure_manufacturing, runtime_dir
from .routes import (
    MANUFACTURING_ADMIN_REVISION_ROUTE,
    MANUFACTURING_DATA_ROUTE,
    MANUFACTURING_ISSUED_EDIT_COMPLETE_ROUTE,
    MANUFACTURING_PARTIAL_QTY_ROUTE,
    MANUFACTURING_REPORT_READY_ROUTE,
    MANUFACTURING_ROUTE,
    MANUFACTURING_STATE_ROUTE,
    MANUFACTURING_TOPFLOOR_BOX_ROUTE,
    MANUFACTURING_TOPFLOOR_TRANSFER_ROUTE,
)
from .workflow import (
    MANUFACTURING_OPERATION_DEFINITIONS,
    MANUFACTURING_PRIME_SYNC_ON_START,
    _load_manufacturing_bundle_cached,
    _manufacturing_is_virtual_unit_row_id,
    _manufacturing_normalize_number,
    _manufacturing_normalize_operation,
    _manufacturing_operation_state_keys,
    _manufacturing_query_params,
    _manufacturing_ready_endpoint_key,
    _manufacturing_selection_state_payload,
    _manufacturing_topfloor_aggregate_bundle,
    _manufacturing_view_bundle,
    _prime_manufacturing_cache_async,
    _prime_manufacturing_cache_worker,
    manufacturing_client_payload,
    manufacturing_module_payload,
    render_manufacturing_module,
)

__all__ = [
    "MANUFACTURING_ADMIN_REVISION_ROUTE",
    "MANUFACTURING_DATA_ROUTE",
    "MANUFACTURING_ISSUED_EDIT_COMPLETE_ROUTE",
    "MANUFACTURING_OPERATION_DEFINITIONS",
    "MANUFACTURING_PARTIAL_QTY_ROUTE",
    "MANUFACTURING_PRIME_SYNC_ON_START",
    "MANUFACTURING_REPORT_READY_ROUTE",
    "MANUFACTURING_ROUTE",
    "MANUFACTURING_STATE_ROUTE",
    "MANUFACTURING_TOPFLOOR_BOX_ROUTE",
    "MANUFACTURING_TOPFLOOR_TRANSFER_ROUTE",
    "MANUFACTURING_ACCESS_USER_IDS",
    "_load_manufacturing_bundle_cached",
    "_manufacturing_is_virtual_unit_row_id",
    "_manufacturing_normalize_number",
    "_manufacturing_normalize_operation",
    "_manufacturing_operation_state_keys",
    "_manufacturing_query_params",
    "_manufacturing_ready_endpoint_key",
    "_manufacturing_selection_state_payload",
    "_manufacturing_topfloor_aggregate_bundle",
    "_manufacturing_view_bundle",
    "_prime_manufacturing_cache_async",
    "_prime_manufacturing_cache_worker",
    "available_production_entries",
    "available_production_numbers",
    "complete_issued_row_edit",
    "configure_manufacturing",
    "latest_production_number",
    "load_partial_quantity_state",
    "load_production_bundle",
    "load_selection_state",
    "manufacturing_client_payload",
    "manufacturing_module_payload",
    "production_folder",
    "render_manufacturing_module",
    "runtime_dir",
    "save_partial_quantity_state",
    "save_selection_state",
    "save_pantolo_missing_description",
    "sync_pantolo_missing_state",
]
