"""Route constants for the manufacturing papers workflow."""

from __future__ import annotations

MANUFACTURING_ROUTE = "/apps/gyartasi-papirok"
MANUFACTURING_DATA_ROUTE = f"{MANUFACTURING_ROUTE}/data"
MANUFACTURING_ADMIN_REVISION_ROUTE = f"{MANUFACTURING_ROUTE}/admin-revision"
MANUFACTURING_STATE_ROUTE = f"{MANUFACTURING_ROUTE}/state"
MANUFACTURING_PARTIAL_QTY_ROUTE = f"{MANUFACTURING_ROUTE}/partial-qty"
MANUFACTURING_REPORT_READY_ROUTE = f"{MANUFACTURING_ROUTE}/report-ready"
MANUFACTURING_TOPFLOOR_BOX_ROUTE = f"{MANUFACTURING_ROUTE}/topfloor-box"
MANUFACTURING_TOPFLOOR_TRANSFER_ROUTE = f"{MANUFACTURING_ROUTE}/topfloor-transfer"
MANUFACTURING_ISSUED_EDIT_COMPLETE_ROUTE = f"{MANUFACTURING_ROUTE}/issued-row-edit-complete"
